version: '3.8'

services:
  line-provider:
    build: ./line-provider
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000

  bet-maker:
    build: ./bet-maker
    ports:
      - "8001:8001"
    environment:
      - HOST=0.0.0.0
      - PORT=8001
      - LINE_PROVIDER_URL=http://line-provider:8000
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/betting
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - line-provider
      - db
      - redis

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=betting
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data


volumes:
  postgres_data:
  redis_data:
